# Generated by Django 5.2.6 on 2025-10-01 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
