# Generated by Django 5.2.6 on 2025-09-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="demo_link",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
