# Generated by Django 5.2.6 on 2025-09-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_tag_review_project_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="vote_ratio",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="vote_total",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
