# Generated by Django 5.2.6 on 2025-09-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_vote_ratio_project_vote_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="demo_link",
            field=models.CharField(
                blank=True, default="default.jpg", max_length=2000, null=True
            ),
        ),
    ]
