# Generated by Django 5.2.6 on 2025-09-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_featured_image_alter_project_demo_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="demo_link",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to=""
            ),
        ),
    ]
