# Generated by Django 5.2.6 on 2025-09-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio']},
        ),
        migrations.AddField(
            model_name='project',
            name='rank_score',
            field=models.FloatField(default=0.0),
        ),
    ]
