# Generated by Django 5.2.6 on 2025-10-01 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_options_project_rank_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', '-title']},
        ),
    ]
