# Generated by Django 5.2.6 on 2025-10-01 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='rank_score',
        ),
    ]
